plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'org.jetbrains.kotlin.jvm' version "2.4.0"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	accessWidenerPath = file("src/main/resources/${archives_base_name}.accesswidener")

	splitEnvironmentSourceSets()

	mods {
		"${archives_base_name}" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs.configureEach {
		setGenerateRunConfig true
	}
}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

repositories {
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
	mavenCentral()
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "maven.modrinth:modmenu:${project.modmenu_version}"
	implementation "maven.modrinth:yeetus-experimentus:${project.yeetus_experimentus_version}"
}

processResources {
	inputs.property "mod_version", mod_version
	inputs.property "mod_id", archives_base_name

	filesMatching("fabric.mod.json") {
		expand "mod_version": mod_version,
				"mod_id": archives_base_name
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

}

jar {
	version = "${mod_version}-${minecraft_version}-fabric"
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}

kotlin {
	jvmToolchain(25)
}