org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

fabric.loom.disableObfuscation=true

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.2-beta
maven_group=com.mikitellurium
archives_base_name=superflatbiomeextension

# Dependencies
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.1
yeetus_experimentus_version=102.0.0